os: linux
language: python

env:
  - SH=bash

python:
  - "3.8"
  - "3.9"

cache:
  pip: true

install:
  - "pip install -r numom2b_preprocessing/requirements.txt"

script:
  - coverage run numom2b_preprocessing/unittests/tests.py

before_install:
  pip install codecov

after_success:
  codecov
